export const logoMap = {
  mercadolivre: { src: "./assets/logos/mercadolivre.png", bg: null },
  soc:          { src: "./assets/logos/soc.svg", bg: "#FFFFFF", darkText: true },
  mazzatech:    { src: "./assets/logos/mazzatech.png", bg: "#FFFFFF", darkText: true },
  zurich:       { src: "./assets/logos/zurich.svg", bg: "#FFFFFF" },
  ufabc:        { src: "./assets/logos/ufabc.svg", bg: "#FFFFFF" },
  etec:         { src: "./assets/logos/etec.png", bg: "#FFFFFF" },
  fiap:         { src: "./assets/logos/fiap.png", bg: null }
};

export const techIconMap = {
  "Java":               "./assets/logos/tech/java.svg",
  "Kotlin":             "./assets/logos/tech/kotlin.svg",
  "Go":                 "./assets/logos/tech/go.svg",
  "Python":             "./assets/logos/tech/python.svg",
  "Spring Boot":        "./assets/logos/tech/spring.svg",
  "Spring Security":    "./assets/logos/tech/spring.svg",
  "Spring Data":        "./assets/logos/tech/spring.svg",
  "Node.js":            "./assets/logos/tech/nodejs.svg",
  "React":              "./assets/logos/tech/react.svg",
  "React Native":       "./assets/logos/tech/react.svg",
  "TypeScript":         "./assets/logos/tech/typescript.svg",
  "JavaScript":         "./assets/logos/tech/javascript.svg",
  "HTML":               "./assets/logos/tech/html5.svg",
  "CSS":                "./assets/logos/tech/css3.svg",
  "HTML/CSS":           "./assets/logos/tech/html5.svg",
  "Bootstrap":          "./assets/logos/tech/bootstrap.svg",
  "AWS":                "./assets/logos/tech/aws.svg",
  "EC2":                "./assets/logos/tech/amazonec2.svg",
  "S3":                 "./assets/logos/tech/amazons3.svg",
  "Lambda":             "./assets/logos/tech/awslambda.svg",
  "CloudWatch":         "./assets/logos/tech/amazoncloudwatch.svg",
  "DynamoDB":           "./assets/logos/tech/amazondynamodb.svg",
  "API Gateway":        "./assets/logos/tech/amazonapigateway.svg",
  "SNS":                "./assets/logos/tech/aws.svg",
  "SQS":                "./assets/logos/tech/amazonsqs.svg",
  "SES":                "./assets/logos/tech/aws.svg",
  "BigQuery":           "./assets/logos/tech/googlecloud.svg",
  "Docker":             "./assets/logos/tech/docker.svg",
  "MLOps":              "./assets/logos/tech/mlops.svg",
  "Claude / Anthropic": "./assets/logos/tech/claude.svg",
  "OpenAI":             "./assets/logos/tech/openai.svg",
  "Google AI / Gemini": "./assets/logos/tech/gemini.svg",
  "DevEx":              "./assets/logos/tech/devex.svg",
  "Test Automation":    "./assets/logos/tech/test.svg",
  "Prompt Engineering": "./assets/logos/tech/prompt.svg",
  "Git":                "./assets/logos/tech/git.svg",
  "GitHub":             "./assets/logos/tech/github.svg",
  "GitLab":             "./assets/logos/tech/gitlab.svg",
  "Jest":               "./assets/logos/tech/jest.svg",
  "ElasticSearch":      "./assets/logos/tech/elasticsearch.svg",
  "MongoDB":            "./assets/logos/tech/mongodb.svg",
  "MySQL":              "./assets/logos/tech/mysql.svg",
  "PyTorch":            "./assets/logos/tech/pytorch.svg",
  "FastAPI":            "./assets/logos/tech/fastapi.svg",
  "PostgreSQL":         "./assets/logos/tech/postgresql.svg",
  "BlenderProc":        "./assets/logos/tech/blender.svg",
  "Blender 3D":         "./assets/logos/tech/blender.svg",
  "YOLOv11":            "./assets/logos/tech/python.svg"
};
